apiVersion: v1
entries:
  wind-river-cloud-platform-deployment-manager:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-12-10T23:01:07.108494214-05:00"
    description: A Helm chart for the Deployment Manager
    digest: f0e3e54e9cffbe6d81f694978dce67d8502b2be6b7c60492d4e6fd02ad0da92b
    icon: https://www.windriver.com/resources/images/wr-logo-red-2018.png
    name: wind-river-cloud-platform-deployment-manager
    urls:
    - wind-river-cloud-platform-deployment-manager-2.0.10.tgz
    version: 2.0.10
generated: "2022-12-10T23:01:07.105628574-05:00"
