apiVersion: v1
entries:
  wind-river-cloud-platform-deployment-manager:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-05-03T17:01:33.040445986-04:00"
    description: A Helm chart for the Deployment Manager
    digest: 668407170e8177acd1c0dd217640020ae1c3eee191c3554671dc5e24de2772e2
    icon: https://www.windriver.com/resources/images/wr-logo-red-2018.png
    name: wind-river-cloud-platform-deployment-manager
    urls:
    - wind-river-cloud-platform-deployment-manager-2.0.8.tgz
    version: 2.0.8
generated: "2022-05-03T17:01:33.0395571-04:00"
